/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tree.h"

bool_t
xdr_PNodo (XDR *xdrs, PNodo *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct Nodo), (xdrproc_t) xdr_Nodo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Nodo (XDR *xdrs, Nodo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->valor))
		 return FALSE;
	 if (!xdr_PNodo (xdrs, &objp->izq))
		 return FALSE;
	 if (!xdr_PNodo (xdrs, &objp->der))
		 return FALSE;
	return TRUE;
}
