/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tree.h"

/*--------------------------------------------*/
void recorre(PNodo n)
{
	if(n!=NULL)
	{
		recorre(n->izq);
		printf("%d ", n->valor);
		recorre(n->der);
	}
}
/*--------------------------------------------*/
void
tree_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	int pone_1_arg1;
	PNodo  *result_2;

#ifndef	DEBUG
	clnt = clnt_create (host, TREE, VTREE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

/*--------------------------------------------*/
	int i;
	for(i=0 ; i<1000 ; i++ )
	{
		pone_1_arg1 = 1+(int) (1000.0*rand()/(RAND_MAX+1.0));
/*--------------------------------------------*/
		result_1 = pone_1(pone_1_arg1, clnt);
		if (result_1 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
/*--------------------------------------------*/
	}
/*--------------------------------------------*/
		
	result_2 = arbol_1(clnt);
	if (result_2 == (PNodo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
/*--------------------------------------------*/
	recorre(*result_2);
/*--------------------------------------------*/
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tree_1 (host);
exit (0);
}
